# Generated by Django 5.2.8 on 2025-11-17 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_livro_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='livros', to='core.categoria'),
        ),
    ]
